services:
  - type: web
    name: classcomp-score
    env: python
    plan: free
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: python pre_start.py && python serve.py
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: EXPORT_FOLDER
        value: /tmp/exports
      - key: PORT
        value: 5000
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: 1
