services:
  - type: web
    name: classcomp-score
    env: python
    plan: free
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: python pre_start.py && python serve.py
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: EXPORT_FOLDER
        value: ./exports
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: 1
      - key: TZ
        value: Asia/Shanghai
      - key: PORT
        fromService:
          type: web
          name: classcomp-score
          property: port
